<a href="https://colab.research.google.com/github/manjimams-2000/Manjimams2000/blob/main/Casestudy_on_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
# Load the dataset
file_path = '/content/House_Pricing.csv'
house_pricing_data = pd.read_csv(file_path)

In [3]:
# Display the first few rows of the dataset
house_pricing_data.head()

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,...,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7129300520,14 October 2017,221900.0,3,1.00,1180.0,5650.0,1.0,No,NaN,...,7,1180.0,0,63,0,98178.0,47.5112,-122.257,1340.0,5650
1,6414100192,14 December 2017,538000.0,3,2.25,2570.0,7242.0,2.0,No,NaN,...,7,2170.0,400,67,1991,98125.0,47.7210,-122.319,1690.0,7639
2,5631500400,15 February 2016,180000.0,2,1.00,770.0,10000.0,1.0,No,NaN,...,6,770.0,0,85,0,98028.0,47.7379,-122.233,2720.0,8062
3,2487200875,14 December 2017,604000.0,4,3.00,1960.0,5000.0,1.0,No,NaN,...,7,1050.0,910,53,0,98136.0,47.5208,-122.393,1360.0,5000
4,1954400510,15 February 2016,510000.0,3,2.00,1680.0,8080.0,1.0,No,NaN,...,8,1680.0,0,31,0,98074.0,47.6168,-122.045,1800.0,7503

In [4]:
# Check for missing values in the dataset
missing_values = house_pricing_data.isnull().sum()
print(missing_values)

ID                                               0
Date House was Sold                              0
Sale Price                                       4
No of Bedrooms                                   0
No of Bathrooms                                  4
Flat Area (in Sqft)                              9
Lot Area (in Sqft)                               9
No of Floors                                     0
Waterfront View                                  0
No of Times Visited                          19489
Condition of the House                           0
Overall Grade                                    0
Area of the House from Basement (in Sqft)        3
Basement Area (in Sqft)                          0
Age of House (in Years)                          0
Renovated Year                                   0
Zipcode                                          1
Latitude                                         1
Longitude                                        1
Living Area after Renovation (in Sqft)           1
Lot Area after Renovation (in Sqft)              0
dtype: int64

In [13]:
numerical_columns = ['Sale Price', 'No of Bedrooms', 'No of Bathrooms', 'Flat Area (in Sqft)',
                     'Lot Area (in Sqft)', 'No of Floors', 'Overall Grade', 'Area of the House from Basement (in Sqft)',
                     'Basement Area (in Sqft)', 'Age of House (in Years)', 'Renovated Year', 'Zipcode',
                     'Latitude', 'Longitude', 'Living Area after Renovation (in Sqft)',
                     'Lot Area after Renovation (in Sqft)']

In [14]:
non_numerical_columns = ['ID', 'Date House was Sold', 'Waterfront View', 'No of Times Visited', 'Condition of the House']

In [15]:
house_pricing_data[numerical_columns] = house_pricing_data[numerical_columns].fillna(house_pricing_data[numerical_columns].median())

In [16]:
house_pricing_data['Date House was Sold'] = house_pricing_data['Date House was Sold'].fillna(house_pricing_data['Date House was Sold'].mode()[0])
house_pricing_data['Waterfront View'] = house_pricing_data['Waterfront View'].fillna('No')
house_pricing_data['No of Times Visited'] = house_pricing_data['No of Times Visited'].fillna('None')
house_pricing_data['Condition of the House'] = house_pricing_data['Condition of the House'].fillna('Good')

In [17]:
house_pricing_data[numerical_columns] = house_pricing_data[numerical_columns].apply(pd.to_numeric, errors='coerce')

In [18]:
categorical_columns = ['Waterfront View', 'No of Times Visited', 'Condition of the House']
house_pricing_data[categorical_columns] = house_pricing_data[categorical_columns].astype('category')

In [19]:
house_pricing_data['Date House was Sold'] = pd.to_datetime(house_pricing_data['Date House was Sold'], errors='coerce')

In [20]:
house_pricing_data['Year Sold'] = house_pricing_data['Date House was Sold'].dt.year
house_pricing_data['Month Sold'] = house_pricing_data['Date House was Sold'].dt.month
house_pricing_data['Day Sold'] = house_pricing_data['Date House was Sold'].dt.day

In [21]:
house_pricing_data.drop(columns=['Date House was Sold'], inplace=True)

In [22]:
house_pricing_data = pd.get_dummies(house_pricing_data, columns=categorical_columns, drop_first=True)

In [23]:
from sklearn.preprocessing import StandardScaler

In [24]:
scaler = StandardScaler()
house_pricing_data[numerical_columns] = scaler.fit_transform(house_pricing_data[numerical_columns])

In [25]:
house_pricing_data.head()

,ID,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),...,Day Sold,Waterfront View_Yes,No of Times Visited_None,No of Times Visited_Once,No of Times Visited_Thrice,No of Times Visited_Twice,Condition of the House_Excellent,Condition of the House_Fair,Condition of the House_Good,Condition of the House_Okay
0,7129300520,-0.866430,-0.398737,-1.447640,-0.979940,-0.228268,-0.915427,-0.564013,-0.734756,-0.658681,...,14,False,True,False,False,False,False,True,False,False
1,6414100192,-0.005939,-0.398737,0.175628,0.533757,-0.189832,0.936506,-0.564013,0.461025,0.245141,...,14,False,True,False,False,False,False,True,False,False
2,5631500400,-0.980490,-1.473959,-1.447640,-1.426426,-0.123244,-0.915427,-1.468651,-1.229979,-0.658681,...,15,False,True,False,False,False,False,True,False,False
3,2487200875,0.173727,0.676485,1.149589,-0.130528,-0.243962,-0.915427,-0.564013,-0.891778,1.397515,...,14,False,True,False,False,False,True,False,False,False
4,1954400510,-0.082161,-0.398737,-0.149026,-0.435445,-0.169600,-0.915427,0.340626,-0.130826,-0.658681,...,15,False,True,False,False,False,False,True,False,False

In [26]:
house_pricing_data.columns.tolist()

['ID',
 'Sale Price',
 'No of Bedrooms',
 'No of Bathrooms',
 'Flat Area (in Sqft)',
 'Lot Area (in Sqft)',
 'No of Floors',
 'Overall Grade',
 'Area of the House from Basement (in Sqft)',
 'Basement Area (in Sqft)',
 'Age of House (in Years)',
 'Renovated Year',
 'Zipcode',
 'Latitude',
 'Longitude',
 'Living Area after Renovation (in Sqft)',
 'Lot Area after Renovation (in Sqft)',
 'Year Sold',
 'Month Sold',
 'Day Sold',
 'Waterfront View_Yes',
 'No of Times Visited_None',
 'No of Times Visited_Once',
 'No of Times Visited_Thrice',
 'No of Times Visited_Twice',
 'Condition of the House_Excellent',
 'Condition of the House_Fair',
 'Condition of the House_Good',
 'Condition of the House_Okay']

In [27]:
print(house_pricing_data.columns.tolist())

['ID', 'Sale Price', 'No of Bedrooms', 'No of Bathrooms', 'Flat Area (in Sqft)', 'Lot Area (in Sqft)', 'No of Floors', 'Overall Grade', 'Area of the House from Basement (in Sqft)', 'Basement Area (in Sqft)', 'Age of House (in Years)', 'Renovated Year', 'Zipcode', 'Latitude', 'Longitude', 'Living Area after Renovation (in Sqft)', 'Lot Area after Renovation (in Sqft)', 'Year Sold', 'Month Sold', 'Day Sold', 'Waterfront View_Yes', 'No of Times Visited_None', 'No of Times Visited_Once', 'No of Times Visited_Thrice', 'No of Times Visited_Twice', 'Condition of the House_Excellent', 'Condition of the House_Fair', 'Condition of the House_Good', 'Condition of the House_Okay']